const scenarios={
 executive:{title:"Executive performance view",label:"Illustrative baseline",values:[86,76,72,82],decision:"BUILD",tone:"success",copy:"Clear decision owner and business outcome; validate the source definitions, then release with an adoption review."},
 selfservice:{title:"Self-service supplier dataset",label:"Illustrative scenario",values:[74,62,58,55],decision:"VALIDATE",tone:"warning",copy:"The value is credible, but definition ownership and repeat-user behavior need evidence before broad release."},
 agent:{title:"AI-assisted exception triage",label:"Illustrative scenario",values:[82,48,64,46],decision:"SEQUENCE",tone:"hold",copy:"Sequence behind data quality, human authority, and evaluation work. A bounded pilot can test the operating contract."},
 urgent:{title:"Urgent dashboard correction",label:"Illustrative scenario",values:[67,92,90,78],decision:"BUILD",tone:"success",copy:"Time-sensitive and low ambiguity. Fix quickly, record the root cause, and prevent recurrence through a reusable control."}
};
const toneMap={success:["var(--soft-lime)","var(--success)"],warning:["#fff3d6","var(--warning)"],hold:["var(--soft-violet)","var(--hold)"],stop:["#ffe6eb","var(--stop)"]};
function derive(){const sliders=[...document.querySelectorAll('.criterion input')];if(!sliders.length)return;const v=sliders.map(x=>+x.value);document.querySelectorAll('.criterion output').forEach((o,i)=>o.textContent=v[i]);const [outcome,evidence,delivery,adoption]=v;let decision='BUILD',tone='success',copy='Outcome, evidence, delivery path, and adoption ownership are strong enough to commit.';if(outcome<45){decision='STOP';tone='stop';copy='The request does not yet justify scarce delivery capacity. Clarify the decision and value before committing.'}else if(evidence<55||adoption<50){decision='VALIDATE';tone='warning';copy='The opportunity is plausible, but one bounded validation should prove evidence readiness or adoption ownership.'}else if(delivery<55){decision='SEQUENCE';tone='hold';copy='Sequence the work behind a dependency, capacity constraint, or release-readiness requirement.'}const box=document.getElementById('disposition');box.style.background=toneMap[tone][0];box.style.borderColor=toneMap[tone][1];box.querySelector('strong').textContent=decision;box.querySelector('strong').style.color=toneMap[tone][1];box.querySelector('p').textContent=copy;updateHero(decision);}
function loadScenario(key){const s=scenarios[key];if(!s)return;document.querySelectorAll('.artifact-tab').forEach(b=>{b.classList.toggle('active',b.dataset.scenario===key);b.setAttribute('aria-selected',b.dataset.scenario===key)});document.getElementById('scenarioTitle').textContent=s.title;document.getElementById('scenarioLabel').textContent=s.label;document.querySelectorAll('.criterion input').forEach((x,i)=>x.value=s.values[i]);derive();}
function updateHero(decision){const map={BUILD:'Ready to commit',VALIDATE:'Prove before scale',SEQUENCE:'Resolve dependency',STOP:'Clarify or stop'};const badge=document.querySelector('.decision-badge');if(badge){badge.textContent=decision;document.getElementById('heroDecisionCopy').textContent=map[decision]||'';}document.querySelectorAll('.gate').forEach((g,i)=>g.classList.toggle('active',i<({BUILD:4,VALIDATE:2,SEQUENCE:3,STOP:1}[decision]||1)));}
document.querySelectorAll('.artifact-tab').forEach(b=>b.addEventListener('click',()=>loadScenario(b.dataset.scenario)));document.querySelectorAll('.criterion input').forEach(x=>x.addEventListener('input',derive));document.getElementById('resetBaseline')?.addEventListener('click',()=>loadScenario('executive'));document.querySelectorAll('.request-card').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.request-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadScenario(b.dataset.scenario)}));document.querySelector('.menu-button')?.addEventListener('click',e=>{const n=document.querySelector('.nav-links');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});loadScenario('executive');
